{
 "title": "HTTP Overview",
 "tags": [ "Http" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "path", "label": "Endpoint", "query": { "query": "label_values(path)" } },
   { "name": "method", "label": "Method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  { "title": "Real World Tapir ZIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(tapir_request_total{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method) > 0"
    },
    {
     "expr": "sum(increase(tapir_request_duration_seconds_sum{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method) \n/ sum(increase(tapir_request_total{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method) > 0"
    },
    {
     "expr": "(sum(increase(tapir_request_total{status!~\"(1|2|3)xx\",path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method) \n/ sum(increase(tapir_request_total{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method)) >= 0\nor (sum(increase(tapir_request_total{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(increase(tapir_request_duration_seconds_sum{path=~\"$path\",method=~\"$method\",phase=\"body\",instance=~\"$instance\"}[$__range])) by (path,method)\n/ sum(increase(tapir_request_total{path=~\"$path\",method=~\"$method\",instance=~\"$instance\"}[$__range])) by (path,method)) >= 0",
     "legendFormat": "{{http_path}}"
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tapir_request_total{instance=\"$instance\",path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(tapir_request_total{status!~\"(1|2|3)xx\",instance=\"$instance\",path=~\"$path\"}[$__range]))\n/ sum(increase(tapir_request_total{instance=\"$instance\",path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(tapir_request_total{instance=\"$instance\",path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  }
 ]
}